[tool]
[tool.poetry]
authors = ["Max Bridgland <mabridgland@protonmail.com>"]
name = "pixcryption"
version = "0.0.1"
[tool.poetry.dependencies]
numpy = "*"
pillow = "*"
pycrypto = "*"
python = "^3.7"
